[project]
name = "codika_dart_services"
version = "0.1.0"
description = "Shared Dart analysis services for Codika projects"
readme = "README.md"
requires-python = ">=3.9"
authors = [
  { name="Codika", email="dev@codika.ai" },
]
license = "MIT"
dependencies = [
    "PyYAML>=6.0",
] 